apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "apache.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  selector:
    app: {{ template "apache.fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
    - port: 80
      nodePort: 30305
      name: rest-https

